apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dubbo-exporter
  name: dubbo-exporter
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dubbo-exporter
    spec:
      containers:
        - command:
            - dubbo_exporter
            - --province=sh
          image: dubbo-exporter:v1.0.1
          imagePullPolicy: IfNotPresent
          name: dubbo-exporter
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
              scheme: HTTP
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 0.5
              memory: 512Mi
            requests:
              cpu: 0.5
              memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always